'use strict'

const rollup = require('rollup')
const babel = require('rollup-plugin-babel')
const closure = require('./plugins/closure-plugin')
const commonjs = require('rollup-plugin-commonjs')
const prettier = require('rollup-plugin-prettier')
const replace = require('rollup-plugin-replace')
const stripBanner = require('rollup-plugin-strip-banner')
const chalk = require('chalk')
const path = require('path')
const resolve = require('rollup-plugin-node-resolve')
const fs = require('fs')
const argv = require('minimist')(process.argv.slice(2))
const Modules = require('./modules')
